truncate table Metadata;
INSERT Metadata (Meta_Sub_Id, Meta_Type_Code, Meta_Sub_Code, Meta_Type_Name, Meta_Sub_Description, Created_By, Created_On, Modified_By, Modified_On, Status) 
VALUES 
(1, N'STA', N'ACT', N'Status', N'Active', 1, NOW(), NULL, NULL, 1),
(2, N'STA', N'INA', N'Status', N'Inactive', 1, NOW(), NULL, NULL, 1),
(3, N'UOM', N'Kg', N'Unit Of Measurement', N'Kilogram', 1, NOW(), NULL, NULL, 1),
(4, N'UOM', N'Lits', N'Unit Of Measurement', N'Litre', 1, NOW(), NULL, NULL, 1),
(5, N'UOM', N'Nos', N'Unit Of Measurement', N'Numbers', 1, NOW(), NULL, NULL, 1),
(6, N'UOM', N'Mts', N'Unit Of Measurement', N'Meter', 1, NOW(), NULL, NULL, 1),
(7, N'UOM', N'Box', N'Unit Of Measurement', N'Boxes', 1, NOW(), NULL, NULL, 1),
(8, N'UOM', N'Ml', N'Unit Of Measurement', N'Milli Litre', 1, NOW(), NULL, NULL, 1),
(9, N'UOM', N'gm', N'Unit Of Measurement', N'Gram', 1, NOW(), NULL, NULL, 1),
(10, N'UOM', N'TON', N'Unit Of Measurement', N'TON', 1, NOW(), NULL, NULL, 1),
(11, N'MTY', N'RM', N'Material Type', N'Raw Material', 1, NOW(), NULL, NULL, 1),
(12, N'MTY', N'SFG', N'Material Type', N'Semi Finished Goods', 1, NOW(), NULL, NULL, 1),
(13, N'MTY', N'FG', N'Material Type', N'Finished Goods', 1, NOW(), NULL, NULL, 1),
(14, N'PLT', N'WH', N'Plant Type', N'Manufacturing', 1, NOW(), NULL, NULL, 1),
(15, N'YRN', N'YES', N'Yes/ No/ NA', N'Yes', 1, NOW(), NULL, NULL, 1),
(16, N'YRN', N'NO', N'Yes/ No/ NA', N'No', 1, NOW(), NULL, NULL, 1),
(17, N'IDT', N'IDTA', N'Id Card Type', N'Adhaar', 1, NOW(), NULL, NULL, 1),
(18, N'IDT', N'IDTV', N'Id Card Type', N'Voter ID', 1, NOW(), NULL, NULL, 1),
(19, N'IDT', N'IDTP', N'Id Card Type', N'Pan Card', 1, NOW(), NULL, NULL, 1),
(20, N'IDT', N'IDTD', N'Id Card Type', N'Driving license', 1, NOW(), NULL, NULL, 1),
(21, N'IDT', N'IDTPA',N'Id Card Type', N'Pass Port', 1, NOW(), NULL, NULL, 1),
(22, N'IDT', N'IDTO', N'Id Card Type', N'Others', 1, NOW(), NULL, NULL, 1),
(23, N'SCY', N'SCYP', N'Supplier Category', N'Product', 1, NOW(), NULL, NULL, 1),
(24, N'SCY', N'SCYS', N'Supplier Category', N'Service', 1, NOW(), NULL, NULL, 1),
(25, N'STY', N'STYI', N'Supplier Type', N'Local', 1, NOW(), NULL, NULL, 1),
(26, N'STY', N'STYL', N'Supplier Type', N'International', 1, NOW(), NULL, NULL, 1),
(27, N'STY', N'STYB', N'Supplier Type', N'Both', 1, NOW(), NULL, NULL, 1),
(28, N'VTY', N'VTYT', N'Vehicle Type', N'Trip/Own', 1, NOW(), NULL, NULL, 1),
(29, N'VTY', N'VTYS', N'Vehicle Type', N'Supplier', 1, NOW(), NULL, NULL, 1),
(30, N'ETY', N'ETYP', N'Employee Type', N'Permanent', 1, NOW(), NULL, NULL, 1),
(31, N'ETY', N'ETYC', N'Employee Type', N'Contract', 1, NOW(), NULL, NULL, 1),
(32, N'EST', N'ESTS', N'Employee Status', N'Suspended', 1, NOW(), NULL, NULL, 1),
(33, N'EST', N'ESTT', N'Employee Status', N'Terminated', 1, NOW(), NULL, NULL, 1),
(34, N'EST', N'ESTR', N'Employee Status', N'Resigned', 1, NOW(), NULL, NULL, 1),
(35, N'VIY', N'VIYI', N'Visitor Type', N'One Day Pass', 1, NOW(), NULL, NULL, 1),
(36, N'VIY', N'VIYC', N'Visitor Type', N'Extended Pass', 1, NOW(), NULL, NULL, 1),
(37, N'TTL', N'TTMR', N'Title', N'Mr', 1, NOW(), NULL, NULL, 1),
(38, N'TTL', N'TTMS', N'Title', N'Mrs', 1, NOW(), NULL, NULL, 1),
(39, N'TTL', N'TTMI', N'Title', N'Miss', 1, NOW(), NULL, NULL, 1),
(40, N'SYM', N'SYM*', N'Symbol', N'*', 1, NOW(), NULL, NULL, 1),
(41, N'SYM', N'SYM@', N'Symbol', N'@', 1, NOW(), NULL, NULL, 1),
(42, N'SYM', N'SYM-', N'Symbol', N'_', 1, NOW(), NULL, NULL, 1),
(43, N'SYM', N'SYM-', N'Symbol', N'-', 1, NOW(), NULL, NULL, 1),
(44, N'DTF', N'DTF', N'Date Format', N'ddmmyyyy', 1, NOW(), NULL, NULL, 1),
(45, N'MST', N'MSTM', N'Marital Status', N'Married', 1, NOW(), NULL, NULL, 1),
(46, N'MST', N'MSTU', N'Marital Status', N'Un Married', 1, NOW(), NULL, NULL, 1),
(47, N'MST', N'MSTD', N'Marital Status', N'Divorced', 1, NOW(), NULL, NULL, 1),
(48, N'MST', N'MSTW', N'Marital Status', N'Widow', 1, NOW(), NULL, NULL, 1),
(49, N'GEN', N'GENM', N'Gender', N'Male', 1, NOW(), NULL, NULL, 1),
(50, N'GEN', N'GENF', N'Gender', N'Female', 1, NOW(), NULL, NULL, 1),
(51, N'GEN', N'GENO', N'Gender', N'Others', 1, NOW(), NULL, NULL, 1),
(52, N'BLD', N'BLDAP', N'Blood Group', N'A+', 1, NOW(), NULL, NULL, 1),
(53, N'BLD', N'BLDBP', N'Blood Group', N'B+', 1, NOW(), NULL, NULL, 1),
(54, N'BLD', N'BLDBN', N'Blood Group', N'B-', 1, NOW(), NULL, NULL, 1),
(55, N'BLD', N'BLDAN', N'Blood Group', N'A-', 1, NOW(), NULL, NULL, 1),
(56, N'BLD', N'BLDOP', N'Blood Group', N'O+', 1, NOW(), NULL, NULL, 1),
(57, N'BLD', N'BLDON', N'Blood Group', N'O-', 1, NOW(), NULL, NULL, 1),
(58, N'BLD', N'BLDABP',N'Blood Group', N'AB+', 1, NOW(), NULL, NULL, 1),
(59, N'BLD', N'BLDABN',N'Blood Group', N'AB-', 1, NOW(), NULL, NULL, 1),
(60, N'CHK', N'CHKI',N'Checkin Status', N'Check In', 1, NOW(), NULL, NULL, 1),
(61, N'CHK', N'CHKO',N'Checkin Status', N'Check Out', 1, NOW(), NULL, NULL, 1),
(62, N'PTY', N'PTYC',N'Party Type', N'Customer', 1, NOW(), NULL, NULL, 1),
(63, N'PTY', N'PTYS',N'Party Type', N'Supplier', 1, NOW(), NULL, NULL, 1),
(64, N'VIY', N'VIYC', N'Visitor Type', N'Delivery Challan', 1, NOW(), NULL, NULL, 2),
(65, N'VIY', N'VIYC', N'Visitor Type', N'Invoice Based', 1, NOW(), NULL, NULL, 2),
(66, N'VIY', N'VIYC', N'Visitor Type', N'Vehicle Entry', 1, NOW(), NULL, NULL, 1),
(67, N'LVL', N'LVL1', N'Level', N'Level 1', 1, NOW(), NULL, NULL, 1),
(68, N'LVL', N'LVL2', N'Level', N'Level 2', 1, NOW(), NULL, NULL, 1),
(69, N'LVL', N'LVL3', N'Level', N'Level 3', 1, NOW(), NULL, NULL, 1),
(70, N'ATY', N'ATYC', N'Activity', N'Create', 1, NOW(), NULL, NULL, 1),
(71, N'ATY', N'ATYU', N'Activity', N'Update', 1, NOW(), NULL, NULL, 1),
(72, N'ATY', N'ATYD', N'Activity', N'Delete', 1, NOW(), NULL, NULL, 1),
(73, N'APS', N'APSC',N'Approval Status', N'Created', 1, NOW(), NULL, NULL, 1),
(74, N'APS', N'APSI',N'Approval Status', N'In Progress', 1, NOW(), NULL, NULL, 1),
(75, N'APS', N'APSA',N'Approval Status', N'Approved', 1, NOW(), NULL, NULL, 1),
(76, N'APS', N'APSR',N'Approval Status', N'Rejected', 1, NOW(), NULL, NULL, 1),
(77, N'SCY', N'SCYP', N'Supplier Category', N'Transporter ', 1, NOW(), NULL, NULL, 1),
(78, N'POV', N'POV1', N'Purpose Of Visit', N'Auditing/Inspection ', 1, NOW(), NULL, NULL, 1),
(79, N'POV', N'POV2', N'Purpose Of Visit', N'Attending Interview ', 1, NOW(), NULL, NULL, 1),
(80, N'POVV', N'POV3', N'Purpose Of Visit', N'Contractor/Temporary Work ', 1, NOW(), NULL, NULL, 1),
(81, N'POVV', N'POV4', N'Purpose Of Visit', N'Customer/Supplier Meeting ', 1, NOW(), NULL, NULL, 1),
(82, N'POVV', N'POV5', N'Purpose Of Visit', N'Client/Partner Meeting ', 1, NOW(), NULL, NULL, 1),
(83, N'POVV', N'POV6', N'Purpose Of Visit', N'Delivery ', 1, NOW(), NULL, NULL, 1),
(84, N'POV', N'POV7', N'Purpose Of Visit', N'Training/Workshop ', 1, NOW(), NULL, NULL, 1),
(85, N'POV', N'POV8', N'Purpose Of Visit', N'Service/Maintenance ', 1, NOW(), NULL, NULL, 1),
(86, N'POVV', N'POV9', N'Purpose Of Visit', N'Sales/Presentation ', 1, NOW(), NULL, NULL, 1),
(87, N'POVV', N'POV10', N'Purpose Of Visit', N'Tour ', 1, NOW(), NULL, NULL, 1),
(88, N'POV', N'POV11', N'Purpose Of Visit', N'Meeting ', 1, NOW(), NULL, NULL, 1),
(89, N'POV', N'POV12', N'Purpose Of Visit', N'Personal Visit ', 1, NOW(), NULL, NULL, 2),
(90, N'POV', N'POV13', N'Purpose Of Visit', N'Government Officials ', 1, NOW(), NULL, NULL, 2),
(91, N'POV', N'POV14', N'Purpose Of Visit', N'Consultation ', 1, NOW(), NULL, NULL, 2),
(92, N'POV', N'POV15', N'Purpose Of Visit', N'Emergency Response ', 1, NOW(), NULL, NULL, 2),
(93, N'POV', N'POV16', N'Purpose Of Visit', N'Others ', 1, NOW(), NULL, NULL, 1),
(94, N'WSV', N'WSVH', N'Work Severity', N'High ', 1, NOW(), NULL, NULL, 1),
(95, N'WSV', N'WSVM', N'Work Severity', N'Medium ', 1, NOW(), NULL, NULL, 1),
(96, N'WSV', N'WSVL', N'Work Severity', N'Low ', 1, NOW(), NULL, NULL, 1),
(97, N'ALL', N'ALL', N'All', N'All ', 1, NOW(), NULL, NULL, 1),
(98, N'PLT', N'WH', N'Plant Type', N'IT', 1, NOW(), NULL, NULL, 1),
(99, N'PLT', N'WH', N'Plant Type', N'Educational Institution', 1, NOW(), NULL, NULL, 1),
(100, N'DCT', N'RET', N'Delivery Challan', N'Returnable ', 1, NOW(), NULL, NULL, 1),
(101, N'DCT', N'NRET', N'Delivery Challan', N'Non Returnable ', 1, NOW(), NULL, NULL, 1),
(102, N'SNT', N'STI', N'Sent Type', N'IN', 1, NOW(), NULL, NULL, 1),
(103, N'SNT', N'STO', N'Sent Type', N'OUT', 1, NOW(), NULL, NULL, 1),
(104, N'MET', N'MTT', N'Message Type', N'Template', 1, NOW(), NULL, NULL, 1),
(105, N'MET', N'MTX', N'Message Type', N'Text', 1, NOW(), NULL, NULL, 1),
(106, N'MET', N'MTI', N'Message Type', N'Image', 1, NOW(), NULL, NULL, 1),
(107, N'MET', N'MTV', N'Message Type', N'Video', 1, NOW(), NULL, NULL, 1),
(108, N'MET', N'MTD', N'Message Type', N'Document', 1, NOW(), NULL, NULL, 1),
(109, N'MET', N'MTA', N'Message Type', N'Audio', 1, NOW(), NULL, NULL, 1),
(110, N'DOC', N'CRC', N'Document Type', N'Company Registration Certificate', 1, NOW(), NULL, NULL, 1),
(111, N'DOC', N'GST', N'Document Type', N'GST Certificate', 1, NOW(), NULL, NULL, 1),
(112, N'DOC', N'ESC', N'Document Type', N'ESI Code', 1, NOW(), NULL, NULL, 1),
(113, N'DOC', N'PFC', N'Document Type', N'PF Code', 1, NOW(), NULL, NULL, 1),
(114, N'DOC', N'PAC', N'Document Type', N'PAN Card', 1, NOW(), NULL, NULL, 1),
(115, N'DOC', N'INS', N'Document Type', N'Insurance', 1, NOW(), NULL, NULL, 1),
(116, N'DOC', N'AAD', N'Document Type', N'Aadhar', 1, NOW(), NULL, NULL, 2),
(117, N'VIY', N'VIYC', N'Visitor Type', N'Work Permit', 1, NOW(), NULL, NULL, 1),
(118, N'POV', N'POV17', N'Purpose Of Visit', N'Work Permit ', 1, NOW(), NULL, NULL, 2),
(119, N'LVL', N'LVL4', N'Level', N'Level 4', 1, NOW(), NULL, NULL, 1),
(120, N'LVL', N'LVL5', N'Level', N'Level 5', 1, NOW(), NULL, NULL, 1),
(121, N'APS', N'APSR',N'Approval Status', N'Cancelled', 1, NOW(), NULL, NULL, 1),
(122, N'YRN', N'NA', N'Yes/ No/ NA', N'n/a', 1, NOW(), NULL, NULL, 1),
(123, N'FEB', N'ECI', N'Feedback', N'Ease of Check-In Process',1, NOW(), NULL, NULL, 1),
(124, N'FEB', N'STP', N'Feedback', N'Staff Friendliness and Professionalism', 1, NOW(), NULL, NULL, 1),
(125, N'FEB', N'WTI', N'Feedback', N'Wait Time', 1, NOW(), NULL, NULL, 1),
(126, N'FEB', N'SPR', N'Feedback',N'Security and Privacy', 1, NOW(), NULL, NULL, 1),
(127, N'FEB', N'OVE', N'Feedback', N'Overall Experience', 1, NOW(), NULL, NULL, 1),
(128, N'VTY', N'VTYE', N'Vehicle Type', N'Employee', 1, NOW(), NULL, NULL, 1),
(129, N'VTY', N'VTYO', N'Vehicle Type', N'Others', 1, NOW(), NULL, NULL, 1),
(130, N'REF', N'EWB', N'Reference Type', N'EWay Bill No', 1, NOW(), NULL, NULL, 1),
(131, N'REF', N'EIN', N'Reference Type', N'EInvoice No', 1, NOW(), NULL, NULL, 1),
(132, N'POVV', N'POV17', N'Purpose Of Visit', N'Work ', 1, NOW(), NULL, NULL, 1),
(133, N'POVV', N'POV18', N'Purpose Of Visit', N'Pickup ', 1, NOW(), NULL, NULL, 1);
;