CREATE TABLE IF NOT EXISTS `Area` (
  `Area_Id` BIGINT AUTO_INCREMENT  NOT NULL,
  `Area_Code` VARCHAR(50) NULL DEFAULT NULL,
  `Area_Name` VARCHAR(255) NOT NULL,
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Area_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;