CREATE TABLE IF NOT EXISTS `Company` (
  `Company_Id` BIGINT AUTO_INCREMENT NOT NULL,
  `Company_Code` VARCHAR(50) NULL DEFAULT NULL,
  `Company_Name` VARCHAR(255) NOT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  `Country_Id` BIGINT NULL DEFAULT NULL,
  `city_Id` BIGINT NULL DEFAULT NULL,
  `State_Id` BIGINT NULL DEFAULT NULL,
  `Mail` LONGTEXT NULL DEFAULT NULL,
  `Host` LONGTEXT NULL DEFAULT NULL,
  `Port` LONGTEXT NULL DEFAULT NULL,
  `User_Name` LONGTEXT NULL DEFAULT NULL,
  `Password` LONGTEXT NULL DEFAULT NULL,
  `Whats_App_Temp` LONGTEXT NULL DEFAULT NULL,
  `Check_Token` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Company_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
