CREATE TABLE IF NOT EXISTS `Customer` (
  `Customer_Id` BIGINT AUTO_INCREMENT NOT NULL,
  `Customer_Code` VARCHAR(50) NULL DEFAULT NULL,
  `Customer_Name` VARCHAR(100) NULL DEFAULT NULL,
  `Country_Id` BIGINT NULL DEFAULT NULL,
  `State_Id` BIGINT NULL DEFAULT NULL,
  `City_Id` BIGINT NULL DEFAULT NULL,
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  `Customer_Image_Name` LONGTEXT NULL DEFAULT NULL,
  `Customer_Image_Url` LONGTEXT NULL DEFAULT NULL,
  `Contact_Person` VARCHAR(100) NULL DEFAULT NULL,
  `Phone_Number` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Address` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;