CREATE TABLE IF NOT EXISTS `Department` (
  `Department_Id` BIGINT AUTO_INCREMENT NOT NULL,
  `Department_Name` VARCHAR(100) NULL DEFAULT NULL,
  `Department_Code` VARCHAR(50) NULL DEFAULT NULL,
  `Hod` BIGINT NOT NULL,
  `Company_Id` BIGINT NOT NULL,
  `Plant_Id` BIGINT NOT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Department_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
