CREATE TABLE IF NOT EXISTS `Feedback` (
  `Feedback_Id` BIGINT AUTO_INCREMENT  NOT NULL,
  `Feedback_Code` VARCHAR(50) NULL DEFAULT NULL,
  `Feedback_Desc` VARCHAR(255) NOT NULL,
  `User_Id` BIGINT NULL DEFAULT NULL,
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Feedback_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;