CREATE TABLE IF NOT EXISTS `Gate` (
  `Gate_Id` BIGINT AUTO_INCREMENT NOT NULL,
  `Gate_Name` VARCHAR(100) NULL DEFAULT NULL,
  `Gate_Code` VARCHAR(50) NULL DEFAULT NULL,
  `Gate_No` VARCHAR(100) NULL DEFAULT NULL,
  `Gate_Incharge_id` BIGINT NULL DEFAULT NULL,
  `Gate_Open_Time` DATETIME(6) NULL DEFAULT NULL,
  `Gate_Close_Time` DATETIME(6) NULL DEFAULT NULL,
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Gate_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
