CREATE TABLE IF NOT EXISTS `Login_History` (
  `Login_History_Id` BIGINT AUTO_INCREMENT NOT NULL AUTO_INCREMENT,
  `User_Id` BIGINT NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `IsActive` BOOL NOT NULL,
  PRIMARY KEY (`Login_History_Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 391663
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
