CREATE TABLE IF NOT EXISTS `Route` (
  `Route_Id` BIGINT AUTO_INCREMENT NOT NULL,
  `Route_Code` VARCHAR(50) NULL DEFAULT NULL,
  `Route_Name` VARCHAR(255) NOT NULL,
  `Route_Desc` LONGTEXT NULL DEFAULT NULL,
  `Route_Distance_In_Km` DECIMAL(10,2) NULL DEFAULT NULL,
  `From_Location` VARCHAR(255) NULL DEFAULT NULL,
  `To_Location` VARCHAR(255) NULL DEFAULT NULL,
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Route_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;
