CREATE TABLE IF NOT EXISTS `State` (
  `State_Id` BIGINT AUTO_INCREMENT NOT NULL,
  `Country_Id` BIGINT NOT NULL,
  `State_Name` VARCHAR(100) NOT NULL,
  `State_Code` VARCHAR(100) NOT NULL,
  `Status` INT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`State_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;