DROP TABLE IF EXISTS `Users`;
CREATE TABLE IF NOT EXISTS `Users` (
  `User_Id` BIGINT NOT NULL AUTO_INCREMENT,
  `User_Code` VARCHAR(20) NULL DEFAULT NULL,
  `User_Name` VARCHAR(100) NOT NULL,
  `Password` longtext NOT NULL,
  `Company_Id` BIGINT NOT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Default_Role_Id` BIGINT NULL DEFAULT NULL,
  `Dept_Id` BIGINT NULL DEFAULT NULL,
  `User_Tel_No` VARCHAR(15) NULL DEFAULT NULL,
  `User_Email` VARCHAR(100) NULL DEFAULT NULL,
  `Status` INT NOT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  `is_blocked` BOOL NULL DEFAULT NULL,
  `user_image_name` LONGTEXT NULL DEFAULT NULL,
  `user_image_url` LONGTEXT NULL DEFAULT NULL,
  `Gate_Id` BIGINT NULL DEFAULT NULL,
  `Secondary_Mobile_No` VARCHAR(15) NULL DEFAULT NULL,
  `Address` VARCHAR(500) NULL DEFAULT NULL,
  `Digital_Sign` VARCHAR(500) NULL DEFAULT NULL,
  `Digital_Sign_Name` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`User_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;