CREATE TABLE IF NOT EXISTS `Vendor_Registration` (
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Gate_Id` BIGINT NULL DEFAULT NULL,
  `Vendor_Reg_Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Vendor_Reg_Code` VARCHAR(50) NOT NULL,
  `Vendor_Name` VARCHAR(255) NULL DEFAULT NULL,
  `Vendor_Reg_Date` DATETIME(6) NOT NULL,
  `Valid_From` DATETIME(6) NULL DEFAULT NULL,
  `Valid_To` DATETIME(6) NULL DEFAULT NULL,
  `Insurance_Valid_From` DATETIME(6) NULL DEFAULT NULL,
  `Insurance_Valid_To` DATETIME(6) NULL DEFAULT NULL,
  `Status_Remarks` LONGTEXT NULL DEFAULT NULL,
  `Status` INT NOT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  `Doc_Status` BIGINT NOT NULL DEFAULT '74',
  PRIMARY KEY (`Vendor_Reg_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;