CREATE TABLE IF NOT EXISTS `Whats_App_Log` (
  `WhatsAppLogId` BIGINT NOT NULL AUTO_INCREMENT,
  `WhatsAppLogData` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `RefCode` VARCHAR(50) NULL,
  `TemplateId` LONGTEXT NULL DEFAULT NULL,
  `SentType` INT NULL DEFAULT NULL,
  `FromContact` VARCHAR(12) NULL DEFAULT NULL,
  `ToContact` VARCHAR(12) NULL DEFAULT NULL,
  `MessageType` INT NULL DEFAULT NULL,
  `DeliveryStatus` INT NULL DEFAULT NULL,
  `MessageTime` DATETIME(6) NULL DEFAULT NULL,
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`WhatsAppLogId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;