CREATE TABLE IF NOT EXISTS `Work_Permit` (
  `Company_Id` BIGINT NULL DEFAULT NULL,
  `Plant_Id` BIGINT NULL DEFAULT NULL,
  `Gate_Id` BIGINT NULL DEFAULT NULL,
  `Work_Permit_Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Work_Permit_Code` VARCHAR(50) NOT NULL,
  `Work_Permit_Date` DATETIME(6) NOT NULL,
  `Dept_Id` BIGINT NULL DEFAULT NULL,
  `Vendor_Reg_Id` BIGINT NULL DEFAULT NULL,
  `Valid_From` DATETIME(6) NULL DEFAULT NULL,
  `Valid_To` DATETIME(6) NULL DEFAULT NULL,
  `Contract_Name` VARCHAR(255) NULL DEFAULT NULL,
  `Work_Organizer` BIGINT NULL DEFAULT NULL,
  `Po_No` VARCHAR(50) NULL DEFAULT NULL,
  `Status_Remarks` LONGTEXT NULL DEFAULT NULL,
  `Doc_Status` BIGINT NOT NULL DEFAULT '74',
  `Status` INT NOT NULL,
  `Created_By` INT NOT NULL,
  `Created_On` DATETIME(6) NOT NULL,
  `Modified_By` INT NULL DEFAULT NULL,
  `Modified_On` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`Work_Permit_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;